### ISSUE TITLE
Responder that can handle multiple responses

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#174]
Should be able to concurrently manage many responses at once.

**Comment by yahgwai** [comment]
A replaced transaction will not be accepted unless it increases the cost by > 10-15% (this is a configurable value, so it's possible that some nodes won't allow replacement at all). I'll call this the *replacement rate*

*First strategy* - no batching:
The responder maintains a queue of transactions, ordered by nonce ascending. They are also always ordered by gas price descending, such that the lowest nonce transaction will always have the highest gas price. This will prevent higher gas price transactions waiting for lower gas price ones.

When a new transaction arrives:
1) According to it's gas price, find what nonce it should have in the queue
2) For all transactions where nonce >= incomingTx.nonce, ordered by nonce ascending
a) increase the nonce by one
b) check the gas price of transaction at nonce + 1. Then set tx[i].gasPrice := max((1 + replacement rate) * tx[i - i].gasPrice, tx[i].gasPrice).
c) set the gas price to be set the gas price of the incoming tx in the same way.

All transactions that have ever been passed to the network must be monitored for until a tx is mined with that nonce, even ones considered replaced. Since it is technically possible for any of these to get mined, and in any order (only nonce order is guaranteed).


*Batching*
Batching two transactions together can be done with a contract like: https://github.com/counterfactual/monorepo/blob/master/packages/contracts/contracts/MultiSend.sol
However this means they will both use the same gas price. Replacing an existing batch with another will increase the gas price of all internal transactions by the replacement rate.

Creating a batch from an existing transaction/batch and an incoming transaction wont affect the nonces of any other transactions. For this reason, if two transactions are similar in price it may be cheaper to batch them together than to apply the replacement fee to all transactions of a higher nonce.

These two strategies can work well together, ie the first strategy can be applied to batches since a batch is just a transaction.

**Comment by bigspider** [comment]
What do you think is the primary goal of this responder? That is, what are we optimizing for?

Without batching, I think this responder should optimize for throughput rather than minimizing fees, as it is probably easier to optimize fees by using a bunch of one-wallet-per-responder. If we have too many transactions to send for the dedicated responders, then we're already in an emergency and so we should probably use high fees.

Do you know if batching might save fees compared to individual transactions (from different wallets)?

Note: that MultiSend contract seems to revert if any of those transactions fails; but I guess it can be done with a different type of call that continues execution even if a call fails?
