### ISSUE TITLE
Batch updates to the block item store.

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#316]
Once #315 is merged, some issues with the current implementation of BlockItemStore are yet to be addressed:

- Lack of type safety
- feels too tightly coupled with the needs of the BlockCache; probably the features of the class should be generalized.
- A class using certain keys would have no knowledge of other classes using the same keys (so they might tamper each other)
- Lack of batch updates (thus a crash might lead to an inconsistent database state when multiple writes happen that should be atomic (e.g. in the BlockCache).

**Comment by yahgwai** [comment]
All points except batch updates have been addressed in #315

**Comment by yahgwai** [comment]
Updates to the block item store should be made in batches. This is because if PISA crashes it should restart at a the correct place.

Possible solution:
1. Start transaction against a blockhash (maybe in the block processor? or the block cache)
2. Add batch items against a blockhash
3. Commit the batch at the end of the round
