### ISSUE TITLE
Watchtower proposal: multiple watchtowers monitoring same channel

### ISSUE THREAD

**Issue by Xekyo** [PISAresearch/pisa#377]
Hey Sergi and Paddy,

Just skimmed your watchtower proposal. Great work!
I may have missed it, but I haven't seen any discussion of multiple watchtowers monitoring the same channel. I explain a scenario below and suggest a few questions that should be considered (if they haven't yet).

Scenario:
Let's say I have a mega-wumbo channel and I want to be extra sure that a watchtower will intervene on my behalf if I go offline. I therefore purchase monitoring of the same channel state by two or more watchtowers.:

1) Is the appointment message unique per watchtower?
2) Would a watchtower operator reassign watching to another watchtower provider (hopefully not)?
3) Would the Justice Transaction be unique per watchtower?
4) I should not be able to prove one of the watchtowers to be in breach if the other intervened.

Cheers,
Mark

**Comment by sr-gi** [comment]
Hey Mark,

we've had some discussion about this topic, even though there's no writeup  yet. The current approach leaves the hiring process to be user dependant (i.e. If the user wants to hire multiple watchers for the same appointment it free to do so), but I think it may be worth including it in the BOLT.

Regarding your questions:

1. In the current approach, no. The appointment is encrypted using the same `key` and `iv` so multiple towers will have the exact same data. There are some proposals around this though: instead of using an `iv` of 0 (as Rusty proposed in his reply) each user could use a `nonce` that he includes within the appointment. That way the encryption of each blob is different for each tower and none of them would learn about having the same data if a breach is not seen. I think it was Conner from Lightning Labs who mentioned this to me.

2. No. One of the approaches we are envisioning is having watching pools where the user will interact with an operator. The operator will manage multiple (and potentially independent) towers. m-out-of-n watchers should be hired to "ensure" a response, but the operator should not provide this data out of his pool (it's financially encouraged no to do so). Currently each tower is independent, and if they can share / leak the data (I can't see a way of preventing that though).

3. This would depend on the approach followed by the tower. In a pay upfront approach, it may not (the justice will be the same for every tower). On the other hand, the bounty approach may have a dedicated output for the tower that could result in a different justice transaction. Ultimately, the user can pick to make it different from every tower by slightly tweaking the transaction.

4. Not completely sure I follow you here. If you mean that given two towers none of them should be able to prove that they share an appointment, then sure, following the nonce approach mentioned in `1`, or tweaking the transaction, that should be possible.

**Comment by Xekyo** [comment]
Hey Sergi,

thanks for your response. IIRC, your proposal mentioned that there should be a way to prove if a watchtower didn't fulfil their assignment. I was chiefly wondering whether you had considered how that would work when you assigned the same transaction to multiple watchtowers.

E.g. both watchtower A and watchtower B are watching my transaction and my channel partner publishes an outdated state. A reacts with the punishment transaction. Now both A and B's assignments should resolve to be "fulfilled" and I should not be able to prove that B didn't fulfil their assignment.
If all watchtowers end up with the same transaction that would likely be the case, but I just wanted to make sure that it had been considered. :)

**Comment by stonecoldpat** [comment]
Hi Mark,

Yeah that is considered. Pretty much if someone can reveal the revocation
secret for that commitment transaction (i.e. publish a justice
transaction), then for all purposes it is considered rescued. Whether
watchtower A or B did it does not really matter.

**Comment by stonecoldpat** [comment]
So in a way, we care more about promising the "post-state" that the client
was saved, as opposed to the specified justice transaction getting in.

Of course, if no justice transaction gets in, then you can show watchtower
A and B were bad bois.
