### ISSUE TITLE
Make all components required for the demo runnable against a local EVM

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#74]
We need to run our demo locally with ganache, using customized versions of Raiden contracts/UI.
The script will:
- compile raiden contracts
- deploy raiden contracts (how to deterministic addresses?)
- start two raiden nodes for A and B
- start pisa
- start raiden-pisa-daemon

**Comment by yahgwai** [comment]
I think we should the scope of this smaller - don't bother with a full script to do this, instead just make the necessary changes to each of the components so that they can be run locally. Eg for pisa this is already the case, but it isnt for the raiden node.

These updated components can then be plugged into whatever script we use for starting the demo. The reason I say this is because I'm gonna work on a script to incorporate anthony's work and it'd better not to duplicate work.

**Comment by bigspider** [comment]
Ok, then it should just be a matter of compiling them (and perhaps copying the binaries in a more convenient location). What endpoint to use (and the contract addresses) can already be specified as a command line param for raiden.

**Comment by yahgwai** [comment]
Great, just boot each component up and check that it behaves as you expect. One thing we'll need to think of is block time. Is there a component in Ganache that allows you to auto mine?

**Comment by bigspider** [comment]
Yep, there is  -b / --blockTime for ganache-cli, which is the block time in seconds.
