### ISSUE TITLE
Add an end to end test for raiden scenario 2

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#83]
As with kitsune, we should have an end to end test which runs actually runs the raiden nodes, opens channels and closes them whilst checking the balance. The raiden nodes have expose a REST api which will make this doable.

**Comment by ali2251** [comment]
I am not sure how long this will take and whether and e2e is needed for a demo since we will be testing it anyway.

**Comment by yahgwai** [comment]
I think this should take a couple of days, now that we have the ability to run the demo against a local network.

Next week we'll be focusing on refactoring the code. An end to end to will help us feel more secure doing this. It will also help us as we develop PISA in the future - we can run the test to see whether the latest PISA is still compatible with raiden.

**Comment by yahgwai** [comment]
For clarity scenario 2 refers to the following:

Start raiden Alice and Bob
Start pisa
Start raiden-pisa-daemon for Alice
Open channel between Bob and Alice
Send funds from Bob to Alice
Take Alice offline
Bob closes channel
Wait for settlement timeout
Restart Alice's node
Observe that she correctly received the payment

**Comment by bigspider** [comment]
Done an initial version in the 63-raiden-demo branch, runnable with "npm run test-raiden". Stille very crude and with some issues to fix:
- Move logs into the /logs folder.
- Make sure that any files created by the scenario are cleaned up before running tests again.
- Use the locally compiled pisa instead of the pisa docker image.
- Understand why the docker container for parity is not getting shutdown at cleanup.
- Possibly, make sure that docker user is not root so that cleanup is easier if there are problems.
- Add some more tests/assertions during the scenario.

Other end-to-end tests could be added as well, for example:
- perform multiple payments, verify that new appointments override older ones.

Lower priority stuff:
- Verify preconditions for the test beforehand (especially all ports being available)
